### ISSUE TITLE
Document the neo4j table format and how to build a custom extractor/model

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#107]

**Comment by jornh** [comment]
From the discussion in https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1569872497220000?thread_ts=1569865635.187900&channel=CGFBVT23V&message_ts=1569872497.220000

> Not sure what you mean by “project source” - is it the GitHub crawler?

In an official demo of lyft’s version of amundsen, I saw a github link on the right panel. Didn’t know this was being automatically populated! We were going to just manually populate it.

- - - - 

I’m not sure the GitHub crawler exists yet as there’s an open issue for it https://github.com/lyft/amundsen/issues/70 ... I just spelunked a bit in the code and put in a few links on the issue. What I put in so far just basically just confirms what you saw in the demo, and - partly - tries to reverse engineer towards a metadata schema. Though you might already figured something similar out, I think putting in the pointers might at least work as notes to eventually document a walk through the code (so essentially a first step towards https://github.com/lyft/amundsen/issues/107)

Feel free to join - and I think we should be able to spec it out between us, possibly with Lyft folks on the side. I think this also has the benefit that it might (un)cover different needs/expectations we might have.

**Comment by jornh** [comment]
Now onto the missing part to resolve this issue, as given in the title, it can be broken down into:

1. Document the neo4j table format 

2. and how to build a custom extractor/model

## 1. Document the neo4j table format

This is the easy part, at least if we cheat a little and do it by example - and just outsource it by point to some existing artifacts. 🙂 So here we go:

Neo4j is a graph database - the metadata schema in Amundsen originated as the model described in https://github.com/lyft/amundsen/blob/6e73684b002f27da757a6cf5101f392ac8a9775f/docs/architecture.md#metadata

To do live exploration of the real Neo4j instance data spin up Quickstart and point your browser to the awesome Neo4j UI at http://localhost:7474 - then you are able to navigate nodes and edges in the graph like shown in this upcoming PR https://github.com/lyft/amundsendatabuilder/pull/120. Try clicking nodes and edges, and you will see the actual attributes on the graph elements ... 

> To be continued ...

**Comment by jornh** [comment]
Now, since the GitHub  xxxxx no crawler ... . so let’s first look at the Databuilder repo at the time of the https://github.com/lyft/amundsendatabuilder/pull/94 PR.

Here’s a rough overall plan [taken from Slack](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1570043511299600?thread_ts=1569955751.243100&channel=CGFBVT23V&message_ts=1570043511.299600) to inspect the existing simple model and extend it further:
> The `airflow - (generates) -> Table` relation is actually implemented using the *application.py* model in [/databuilder/models/application.py#L22](https://github.com/jornh/amundsendatabuilder/blob/177120f69b82c5f4b246a420709b585dbf71c55a/databuilder/models/application.py#L22).
>
> If you generalize Applications/services to become “transformers” with optional input(s) and output(s) you have your consuming service users & more. It basically moves the Neo4j backend closer to what Atlas offers, WDYT? Feel free to create a GitHub issue for it

If you open the link in the plan above in a new window you can follow along here. Let’s do it! 

You’ll notice that the model is actually hardcoded to only handle Airflow as the application. To understand the model you’ll need to know that it inherents from `Neo4jCsvSerializable`. That class produces two temporary CSV files. One file holds *nodes* the other *relations* we want to ingest into Neo4j. Databuilder `models/` generally iterate over records from an Extractor to build something for a Loader that then is handed to a Publisher as shown in the README [diagram](url). You probably already guessed that here those are Neo4jLoader() and ...Publisher().

> To be continued ...
