### ISSUE TITLE
Docker Compose has Port Conflicts for Port 5000 on macOS Monterey

### ISSUE THREAD

**Issue by cmpadden** [amundsen-io/amundsen#1813]
Unfortunately, the latest version of macOS Monterey uses port 5000 for the internal application Control Center. This causes a port conflict error to be thrown when running the Amundsen Docker instances.

## Expected Behavior

Running `docker-compose -f docker-amundsen.yml up` on macOS Monterey should not product port conflict errors.

## Current Behavior

```
> docker-compose -f docker-amundsen.yml up
Starting neo4j_amundsen ... done
Starting es_amundsen    ... done
Starting amundsensearch   ... done
Starting amundsenmetadata ... done
Recreating 1db7859d4b07_amundsenfrontend ... error

ERROR: for 1db7859d4b07_amundsenfrontend  Cannot start service amundsenfrontend: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use

ERROR: for amundsenfrontend  Cannot start service amundsenfrontend: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

## Possible Solution

We should be able to change services using port 5000 to some other port for local development.

## Your Environment

<img width="245" alt="image" src="https://user-images.githubusercontent.com/5807118/163467332-025297b2-6797-4add-b97f-468854ff0639.png">

```
> lsof -i :5000
COMMAND   PID          USER   FD   TYPE  NODE NAME
ControlCe     ...   IPv4   0t0  TCP *:commplex-main (LISTEN)
ControlCe     ...  IPv6    0t0  TCP *:commplex-main (LISTEN)
```

**Comment by TomKlimovski** [comment]
Bump. I ran into this issue today as well.

**Comment by DSamuylov** [comment]
I can confirm that the issue still remains.

**Comment by yoku2010** [comment]
I was also facing the same issue.

Screenshot of error:
<img width="1067" alt="Screenshot 2022-07-24 at 9 58 31 PM" src="https://user-images.githubusercontent.com/1465530/180657576-834c9133-0f6d-4ee0-aa8d-ff833e6e1b79.png">

This was apparently due to the new AirPlay functionality. Control Center stops listening to those ports when I turned off “AirPlay Receiver” in the “Sharing” System Preference.

Screenshot of solution:
<img width="664" alt="Screenshot 2022-07-24 at 10 08 41 PM" src="https://user-images.githubusercontent.com/1465530/180657631-519535f6-381a-4ac6-a641-d882a9b08acb.png">

Now everything is working fine.

__I am wondering, why apple choose such a popular port.__

**Comment by nickjeffrey** [comment]
This same issue also affects any environment using a virtual machine running under the Nutanix AHV virtualization hypervisor, because the Nutanix Guest Tools agent uses port 5000.

**Comment by cpwillis** [comment]
Just came across the same issue (Flask Default Port: 5000);

> IANA actually assigns port 5000 to "commplex-main", so really any other service that's using that port is violating the official assignment
- [Apple takes over port](https://news.ycombinator.com/item?id=29006861)
- [IANA Assignment](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5000)
- [AirPlay Receiver Confirmed](https://news.ycombinator.com/item?id=29305025)

**Comment by basavyr** [comment]
Wow thanks a lot for the findings @yoku2010 . I have stumble upon this one using my Flask app
