### ISSUE TITLE
Error running Neo4jCsvPublisher

### ISSUE THREAD

**Issue by femi-anthony** [amundsen-io/amundsen#2094]
I'm getting an error when trying to publish CSV data to an empty neo4j database:

```
        job = DefaultJob(
            conf=job_config, task=DummyTask(), publisher=Neo4jCsvPublisher()
        )
        job.launch()
```

```
    ...
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} 
{message: Invalid constraint syntax, ON and ASSERT should not be used. 
Replace ON with FOR and ASSERT with REQUIRE. (line 2, column 1 (offset: 13))
"            CREATE CONSTRAINT ON (node:Table) ASSERT node.key IS UNIQUE"
             ^}

```
Version of libraries

```
amundsen-common==0.26.2
amundsen-databuilder==7.4.3
amundsen-rds==0.0.7
neo4j==5.5.0
neo4j-driver==4.4.10
```
 

## Expected Behavior

No errors

## Current Behavior

Exception occurs
```
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} 
{message: Invalid constraint syntax, ON and ASSERT should not be used. 
Replace ON with FOR and ASSERT with REQUIRE. (line 2, column 1 (offset: 13))
"            CREATE CONSTRAINT ON (node:Table) ASSERT node.key IS UNIQUE"
             ^}
```
## Possible Solution

Change 

`CREATE CONSTRAINT ON (node:Table) ASSERT node.key IS UNIQUE`

to

`CREATE CONSTRAINT FOR (node:Table) REQUIRE node.key IS UNIQUE`

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amundsen version used: 
amundsen-common==0.26.2
amundsen-databuilder==7.4.3
amundsen-rds==0.0.7
* Data warehouse stores:
neo4j==5.5.0
neo4j-driver==4.4.10
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by kristenarmes** [comment]
Hi @femi-anthony, I just took a look and it looks like this syntax is unfortunately no longer valid in Neo4j v5. Right now we don't have specific compatibility for 5 in the publisher. We at Lyft are planning to upgrade in the near future, so we will either address this then, or feel free to take a look at it yourself. The solution should either be backwards compatible or else a new publisher may be required since others are using older versions of Neo4j.

If you are interested in using a faster publisher (that will have the same issue for now) check out [neo4j_csv_unwind_publisher.py](https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/publisher/neo4j_csv_unwind_publisher.py), this is the one we will make compatible with v5 (or create a new version of) when we work on it.

**Comment by femi-anthony** [comment]
@kristenarmes - thanks for your response. Is there now a GA version of Amundsen that is compatible with Neo4j V5 ?
I just overrode the class for our implementation locally to resolve the issue.

**Comment by kristenarmes** [comment]
As far as I'm aware there hasn't been open source development for compatibility with Neo4j v5 yet. We would like to work on this but it is not in our immediate plans, we also welcome contributors toward this goal.
