### ISSUE TITLE
Frontend configurations to be set using API

### ISSUE THREAD

**Issue by verdan** [amundsen-io/amundsen#50]
In order to support all the customizations of the frontend i.e., the logo path etc (mentioned [here](https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/static/js/config/config-default.ts)) when installed using a pip package (already compiled), we need to pass those configs from backend and store them in React's store and use them instead of hardcoding them on frontend .js file. 

@ttannis @danwom FYI.

**Comment by markgrover** [comment]
@ttannis @danwom do you have any thoughts here? Would really appreciate your help.

**Comment by danwom** [comment]
Customizing the frontend currently requires a rebuild and redeploy. 

I can see the use case for a config API, but even that will have great limitations. For example you wouldn't be able to customize any of the colors, fonts, or images. Additionally some of our configs are set as JavaScript functions (generating the Explore SQL link for example), so you can't simply serve some JSON from an API. Though, I would like to move those function configs to the Python layer.

There is some non-trivial work to refactor the app to use a config API. There are some downsides such as additional latency (can't render anything until configs are fetched), and an external dependency (if the config server breaks, amundsenfrontend breaks).

**Comment by ttannis** [comment]
To add to Daniel's comment, I'd like to highlight a specific concept -- the desire to use the pre-built React application source **and** be able to customize it are concepts that don't fit well together because the customizations need to be in place before the React application source is built so that they can be included.

This is why we don't use the pre-built source at Lyft, and why we used to exclude it from prebuilt application source. We anticipated it would not provide value to anyone who wants to customize their application -- which is most people. 

@verdan would you be interested in us helping you explore some of the ideas on this thread from the slack channelr: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1572454944194100

**Comment by verdan** [comment]
With the new logo of Amundsen coming, white-labeling I can understand, the themes, fonts etc. but defining the feature flags, keys, parameters etc., as frontend config is something I am not in favor of.

I would still like to have the feature flags like the followings coming directly from the backend. 
```
  badges: {},
  browse: {
    curatedTags: [],
    showAllTags: true,
  },
  editableText: {
    tableDescLength: 750,
    columnDescLength: 250,
  },
  google: {
    enabled: false,
    key: 'default-key',
    sampleRate: 100,
  },
  indexUsers: {
    enabled: false,
  },
  logoPath: null,
  mailClientFeatures: {
    feedbackEnabled: false,
    notificationsEnabled: false,
  },
```

**Comment by verdan** [comment]
We at Stemma just published a step-by-step guide to getting a fully customized enterprise deployment of Amundsen, that will help you modify the frontend (including CSS+JS) and the Flask configuration pretty easily.  

https://medium.com/stemma/amundsen-deployment-best-practices-740a1800518e
