### ISSUE TITLE
Feature Proposal: Use discovery API for mode dashboard integration

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#607]
## Expected Behavior or Use Case
Switch to use the new [Discovery API](https://mode.com/help/articles/discovery-api) for mode analytics dashboard metadata ingestion which is way more performant.

## Service or Ingestion ETL

databuilder

## Possible Implementation

Switch to use the new discovery API

## Context
Currently the mode dashboard integration with Amundsen is built on top of API which is not for batch ingestion. We have worked with the team  from Mode which they have released the latest discovery API for dashboard integration.

**Comment by feng-tao** [comment]
cc @youngyjd

**Comment by youngyjd** [comment]
Update on this issue:

By now, all extractors are relying on Mode Discovery API except [ModeDashboardUserExtractor](https://github.com/amundsen-io/amundsen/blob/31e778844937537c666712d632b04cc01785e794/databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_user_extractor.py) because the discovery membership endpoint throws 503 error. Mode team is still working on it.
