### ISSUE TITLE
Data Loader Scripts Issue

### ISSUE THREAD

**Issue by debbielee1996** [amundsen-io/amundsen#618]
## Expected Behavior
Started the 4 containers via the following command:
sudo docker-compose -f docker-amundsen-local.yml up --build -d
![image](https://user-images.githubusercontent.com/62943444/89999907-08f10200-dcc2-11ea-94e5-f619d26b845b.png)

Next, I have tried running 2 scripts:
1. I have edited /example/scripts/**sample_mssql_metadata.py** as per:
![image](https://user-images.githubusercontent.com/62943444/89999328-38533f00-dcc1-11ea-8b5e-8fac3841de48.png)

2. Ran the **sample_data_loader.py** without changing anything in the script

## Current Behavior
A snippet of the entire error message. I believe it has got to do with elasticsearch

WARNING:elasticsearch:PUT http://localhost:9200/tables1fc649e9-9970-4933-a79b-223d72e7e69d [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
	(self._dns_host, self.port), self.timeout, **extra_kw
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
	raise err
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
	sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 212, in perform_request
	method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
	method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 379, in increment
	raise six.reraise(type(error), error, _stacktrace)
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
	raise value
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
	chunked=chunked,
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
	conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
	self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
	self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
	self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
	self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
	self.connect()
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
	conn = self._new_conn()
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
	self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0d9d19e7b8>: Failed to establish a new connection: [Errno 111] Connection refused

## Steps to Reproduce

1. _sudo docker-compose -f docker-amundsen-local.yml up --build -d_ to start docker-compose service
2. modified _sample_mssql_metadata.py_
3. had the environment set up proper
![image](https://user-images.githubusercontent.com/62943444/90000085-46ee2600-dcc2-11ea-8958-769d6b88d40e.png)
4. _python3 example/scripts/sample_mssql_metadata.py_ gave the error

## Context

Appreciate any help because this is the most crucial part of the data catalogue... thank you :)

## Your Environment

* Amunsen version used: latest version I believe 
* Ubuntu 18.04 LTS

**Comment by jornh** [comment]
Yes, you mention 4 containers but there are actually 5 of them including `es_amundsen` - so that one didn't come up cleanly as your error also indicates.

Check troubleshooting steps related to ElasticSearch in the Quickstart guide (https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#troubleshooting) + check that you're not constrained on resources memory etc.

**Comment by debbielee1996** [comment]
I'm not sure if the troubleshooting steps are relevant, because when I ran the docker-compose file there were no error messages:
![image](https://user-images.githubusercontent.com/62943444/90083907-629b1000-dd46-11ea-9bee-7e93754ceb77.png)
In fact, starting es_amundsen had no issues. However, that container is not reflected in sudo docker ps, unless I restart the docker-compose:
![image](https://user-images.githubusercontent.com/62943444/90085104-b8bd8280-dd49-11ea-87ee-eb1b669c2e4a.png)

However, when I run the script to upload mssql, it somehow will cause the es_amundsen container to crash again, leaving it to 4 containers. There are no error messages anywhere apart from the below when I run python3 sample_mssql_metadata.py
![image](https://user-images.githubusercontent.com/62943444/90085195-ec001180-dd49-11ea-8711-a4a4d651f079.png)

I am facing the same issue as #3 in https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#troubleshooting but there seems to be no step to troubleshoot for that issue. Please help, thank you :)

**Comment by jornh** [comment]
Thank you for providing good informative posts on what’s happening. An example for others to follow! Much better to work with than “it doesn’t show up in the UI - what’s wrong?” type of requests for help with troubleshooting 👍 

Clearly the ES container dies, indicated by:

> At the same time I am unable to connect to localhost:9200

I’d imagine that test will fail also before you run the databuilder load, meaning databuilder failing is just a symptom not the cause.

 What does `docker logs` For the ElasticSearch container tell you? You’ll have to use that to see any errors since you run Docker compose with the `-d` option.

I notice you run Docker under sudo. The ES container runs with a volume mount. This can cause problems if user id in the container doesn’t have access to the mapped files on your host OS.

The volume mount:
https://github.com/amundsen-io/amundsen/blob/2c466a0a362a82c3fbc6b0f93bc53aafa59e906d/docker-amundsen-local.yml#L32

**Comment by debbielee1996** [comment]
Thank you for the response! I managed to resolve it by following #1 of https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#troubleshooting

Additionally, what do you mean by this:
![image](https://user-images.githubusercontent.com/62943444/90098663-51182f00-dd6b-11ea-8a5b-a923a58761ae.png)

I have to run docker under sudo, otherwise I will get the prompt "permission denied".

**Comment by jornh** [comment]
Great it's resolved! Guess the issue can be closed then

*"Have to run docker under sudo ..."* depends on the configuration of your environment. I don't need to in mine: https://www.google.com/search?q=docker+no+sudo+ubuntu - as I saw you noted Ubuntu as your environment. Running as root or not with docker each comes their pros and cons.

About the volume mapping: https://www.google.com/search?q=docker+volume+access+denied If you read a bunch of these you'll see all kinds of woes and that much of it is linked to "to sudo or not".

Anyway it turned out the volume mapping was not the problem in this case. I was just speculating and jumping ahead too early. It was one of "the usual problems" already under troubleshooting. It was just masked by you not seeing any logs due to the `-d` flag you had on docker-compose.

**Comment by debbielee1996** [comment]
Awesome! Thank you so much for your help 👍
