### ISSUE TITLE
generate column-pointed URL

### ISSUE THREAD

**Issue by higee** [amundsen-io/amundsen#651]
## Expected Behavior or Use Case

Currently, the URL is created per table. For instance, when we have a table in Postgres with

* database : test_db
* schema : test_schema
* table: test_table
* columns:
    * test_column1
    * test_column2
             ⋮

`https://amundsen.something.com/table_detail/test_db/postgres/test_schema/test_table`

But I just thought it would be better if we can add one more level, i.e. column to it so that the URL becomes

`https://amundsen.something.com/table_detail/test_db/postgres/test_schema/test_table/test_column1`

## Service or Ingestion ETL

I think frontend maybe?

## Context

I received a feedback from one of my colleagues asking whether this is possible. He wanted to share a URL of specific table with more than 20 columns to another colleague. Given the number of columns, it seemed better to have an anchor link per column so that by opening the link it lands on the column directly.

**Comment by ttannis** [comment]
A new URL would direct to a new page, and we don't have plans to expose individual pages for columns so they aren't something that can be linked to. 

The core of this issue seems to be that the user wanted a more efficient way to find a particular column. We have current plans to improve column the column UI such that users can sort, and future plans to even add filters to column UI as well. We believe those features to be the ideal support to provide to allows users to more easily interact with columns.

**Comment by jornh** [comment]
> A new URL would direct to a new page, and we don't have plans to expose individual pages for columns so they aren't something that can be linked to.

@ttannis agree 💯 that introducing individual pages for columns would be undesirable. It doesn’t have to be implemented with that tough.

If those deep links were in the form of `#` fragment links like `https://amundsen.something.com/table_detail/test_db/postgres/test_schema/test_table#test_column1` it could just work as “scroll this column into view” - preferably with a visual highlight effect. E.g. column filtering as you suggest would make it very clear, but depending on filter UI Implementation could also have a risk of misleading the person receiving the deep link that the given table only has this one column because they didn’t apply the filter themselves.

The deep links could be added to notifications sent out on “request info on column level”.

A little more context [here on Slack](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1597917345004000?thread_ts=1597911972.003700&channel=CGFBVT23V&message_ts=1597917345.004000)

**Comment by ttannis** [comment]
Thanks @jornh Will get some additional eyes on this from maintainers to ensure my perspective alone doesn't make the call here.

**Comment by higee** [comment]
My bad. I mentioned anchor in the Slack link and instead suggested creating a sub-page per column. What @jornh suggested sounds neat. Thanks for the correction.

**Comment by ttannis** [comment]
@jornh thanks for comment, which led to additional discussion on this feature. Here are next steps/requirements:

1. Introduce a button that will generate the link to share, e.g. `https://amundsen.something.com/table_detail/test_db/postgres/test_schema/test_table#test_column1`
2. When the table page loads, the application checks if there is a column then scrolls to it and expands it.
