### ISSUE TITLE
Support for showing lineage of table across ETL's in a data warehouse

### ISSUE THREAD

**Issue by apoorva007** [amundsen-io/amundsen#69]
Hey, 
Wanted to understand if there is a way to push table lineage related metadata to amundsen. 
Couldn't find any related documentation. If someone can point towards it, that would be really helpful

**Comment by jornh** [comment]
2nd option above has moved a bit forward with merge of https://github.com/lyft/amundsendatabuilder/pull/126 as far as I can see this means with Neo4j https://github.com/lyft/amundsen/issues/69#issuecomment-502841152 is essentially implemented so you can build a Databuilder job which will build lineage in Amundsen Metadata service. 

Submitting a  PR to ingest some sample data modeled after previous sample ingestion PRs seems like a good `good first issue` if you have Python skills and want to get your hands dirty and move this feature forward sooner rather than later!

If you have React skills https://github.com/lyft/amundsenfrontendlibrary/issues/110 might be what you want to look at
