### ISSUE TITLE
Add TableLastUpdatedExtractor for BigQuery

### ISSUE THREAD

**Issue by jinhyukchang** [amundsen-io/amundsen#73]
Currently we have HiveTableLastUpdatedExtractor that figures out when the table is last modified for Hive. This issue is to support the same feature to BigQuery.

**Comment by manesioz** [comment]
Hi! On the docs we can see that for `TableLastUpdated`: 

> you will need access to history that provides information on when the last data write happened on a given table. 

My guess is the implementation will have to leverage `LAST_MODIFIED_TIME ` from the [`INFORMATION_SCHEMA`](https://cloud.google.com/bigquery/docs/information-schema-datasets)? Any thoughts on how to implement this?

**Comment by sagar-raythatha** [comment]
Hi,

I have done this within the BigQueryMetadataExtractor, since the api call in which BigQueryMetadataExtractor making, provides the Last Modified details.

` last_modified_time=table.get('lastModifiedTime', '')`

However, I am not sure how to bring this to the UI. Can anyone give some direction for that?
