### ISSUE TITLE
amundsendatabuilder "leaks" dev dependencies

### ISSUE THREAD

**Issue by astahlman** [amundsen-io/amundsen#80]
amundsendatabuilder [declares](https://github.com/lyft/amundsendatabuilder/blob/b480d0087a32a99c40714ffb3042ba3d529d5a77/setup.py#L21) an `install_requires` dependency on every package from `requirements.txt`.

This means that all consumers of this package must accept transitive dependencies on the specific versions of every package in amundsendatabuilder's development environment. For example, consumers of amundsendatabuilder are forced to install [a specific version of flake8](https://github.com/lyft/amundsendatabuilder/blob/b480d0087a32a99c40714ffb3042ba3d529d5a77/requirements.txt#L4), even though this package doesn't actually need flake8.

Instead, we should declare concrete dependencies needed for development in `requirements.txt` and put the dependencies needed to install the package in `setup.py`. See also [this SO post](https://stackoverflow.com/a/49684835/895769) for one approach to reduce duplication between the two files: instead of having `setup.py` read `requirements.txt`, we can do the opposite and have `requirements.txt` reference the dependencies in `setup.py` through the special dot syntax.

**Comment by feng-tao** [comment]
cc @verdan

**Comment by verdan** [comment]
Agreed! had the same impression when we proposed this solution, as we are installing a lot of test requirements because of this. 
The main problem to have the duplicated requirements is like most of the times people introduce the dependencies in one place and forget to do that in other. 
This pip install -e things is a nice one, and can also think about this: https://stackoverflow.com/a/20720019

**Comment by feng-tao** [comment]
I think we fix this issue long back.
