### ISSUE TITLE
Feature Proposal: Feast databuilder

### ISSUE THREAD

**Issue by szczeles** [amundsen-io/amundsen#815]
## Expected Behavior or Use Case

[Feast](https://feast.dev/) is a project aiming to create flexible feature store implementation for Machine Learning modelling. One of its components, [Feast Core](https://github.com/feast-dev/feast/tree/master/core) is just a features metadata storage. Feast lacks UI interface that could be used for Data Scientists to collaborate on the feature sets, their readiness for modelling (dev/test/beta/prod) and descriptions. I've been experimenting with Amundsen and the Frontend features seem ideal for the case if feature sets are presented as tables and entities/features as columns. Search, preview, editable descriptions, ability to show statistics - it's all super useful in this case.

## Service or Ingestion ETL

* databuilder

## Possible Implementation

* I have the implementation almost ready and happy to contribute in a week or so
* It is simple implementation of `databuilder.extractor.base_extractor.Extractor` that connects to Feast Core API (gRPC) and gets the projects, featuresets and features

**Comment by feng-tao** [comment]
that will be great! thanks @szczeles

**Comment by ug911** [comment]
@szczeles - I have been researching about using a feature store like Feast and Amundsen for the UI layer for exactly the same reasons as you have pointed out. 

I have a few questions about Feast and Amundsen - 
- Is your Feast deployment in Google or Amazon cloud? 
- By connecting Feast Core (Registry) to Amundsen, would a user be able to discover FeatureTables and Entities in Online as well as Offline Store provided by Feast?
- When a user uses the Features through Feast SDK, can Amundsen record or assist in the process?

**Comment by szczeles** [comment]
@ug911 My Feast (and Amundsen) are installed on on-premise k8s cluster, but the only requirements is the access to gRPC port from the system you will run Amundsen's Databuilder on, so any cloud env should work as well.

> By connecting Feast Core (Registry) to Amundsen, would a user be able to discover FeatureTables and Entities in Online as well as Offline Store provided by Feast?

In my project only Offline store is in use, but - if I'm not mistaken - the FeatureTables definitions are same for both stores. Basically, if FeatureTable is available via `client.list_feature_tables()` on any Feast project, its details will be pushed to Amundsen.

> When a user uses the Features through Feast SDK, can Amundsen record or assist in the process?

Currently the usage of Features is not tracked (only creation/update), maybe there would be some option to add "audit logs" on Feast and use them to analyze the Features popularity, but I didn't investigate it.

**Comment by ug911** [comment]
@szczeles - Thanks for your response. I have a few questions about the Amundsendatabuilder and the deployment on AWS Cloud. 

- Where do you run databuilder jobs? Can they be run on EKS? 
- How often does one have to run databuilder jobs? Since they just read the metadata, I am assuming that run that more frequently than metadata changes
- How does one consume the data they find? With Feast SDK using features in Online or Offline setting is straightforward, how does that work with Amundsen?

My data infrastructure has many **Postgres** tables that are extracted to AWS S3 where they are processed through several ETL steps using **Athena** to make final Fact tables that are loaded into **Redshift**. 
- Should I be making databuilder jobs for Postgres tables, Athena tables, Redhshift Tables? 
or 
- Only for my final tables since they contain all the data and I do not want people using Postgres or Athena for querying?
- Since **Amazon Glue** also automatically keeps a tab on all these three sources, writing a job for that should be able to get everything at once. 
- - What are your thoughts on how Amundsen ensures that metadata duplication is avoided?

I am also curious if someone finds Feast features through Amundsen, can they only go back and use them for Serving/Training for can they also be used directly in dashboards?

**Comment by szczeles** [comment]
@ug911 I'm afraid the discussion is going a bit off-topic, but I'm happy to help anyway. My Databuilder jobs are started as Kubeflow Pipelines jobs (or Airflow DAGs in another project), both can run on EKS (well, you can even run it as CronJob, why not?). I run the workflow every hour, but the frequency can be increased. For example - if someone edits the description via Frontend, it takes a bit of time to get Search reloaded (Elasticsearch reingested), so I'm thinking about doing it every 10 minutes in the near future.

Regarding your warehousing setup - in my opinion you should expose only the final tables in Amundsen (Redshift in your case). This is actually what I do in the Feast setup - the features are built from different datasources, but only Feast metadata are exposed, because these are intended to be used by final users (Data Scientists). Adding more underlying databases, however possible, it can be misleading.
