### ISSUE TITLE
Creating users in the metadata graph

### ISSUE THREAD

**Issue by AustinBGibbons** [amundsen-io/amundsen#852]
Hello hello, I am not sure if this is a feature request or a bug report, but new users are not added to the metadata graph

## Expected Behavior
When a new user is created, they are registered within the metadata graph

## Current Behavior

1. We assign a user in Okta
2. User visits the website for the first time
3. Metadata service logs ```metadata_service.exception.NotFoundException: User email@plaid.com not found in the graph```

This causes the user to not have bookmarks

## Possible Solution
Should the user be automatically added to the metadata graph, upon signing in via okta?

## Environment

Deployed via helm using 

```
  image: amundsendev/amundsen-metadata-oidc
  imageTag: 2.5.5
```

I also added

```
        - name: FLASK_OIDC_CLIENT_SECRETS
          value: /etc/client_secrets.json
        - name: OIDC_CLIENT_SECRETS
          value: /etc/client_secrets.json
```

to the deployment-metadata, as it wasn't functioning otherwise (getting a "could not find config/client_secret.json" error)

**Comment by feng-tao** [comment]
@AustinBGibbons thanks for reporting, I think it is an issue combination of FE and metadata. So in order to use bookmark, it indeed requires the user node to be available in the graph, there are couples of issues / questions:
1. should we turn on bookmark if indexUser is disabled (meaning user profile is closed)? At Lyft, we indexed every FTE in the company into the graph, but it is not the case for common deployment as users info may not be able to expose to Amundsen.
2. should we create user when creating bookmark if the user is not in the graph?
3. We shouldn't called the metadata in frontend (https://github.com/amundsen-io/amundsenfrontendlibrary/blob/ccfd2d6b82957fef347e956b243e4048c191fc0d/amundsen_application/api/v0.py#L32) to get the user page if user profile is not enabled.

cc @verdan curious to know what you think as well.

**Comment by AustinBGibbons** [comment]
Can I preemptively create "users", before registering them through okta? I will consider doing that for now, though it will be harder to onboard new users

**Comment by verdan** [comment]
@AustinBGibbons @feng-tao we have the same issue at ING. We can not pre-register all the users in the system/graph/metadata because of a number of limitation (one being we can not scrap the Active Directory and create 52k entries in our graph). Below is my solution:

Use this function in metadata repository 🙂 :  https://www.amundsen.io/amundsen/metadata/docs/configurations/#user_detail_method-optional

In this function, we first check if the user is available in our metadata, then return the details, if not, then create in the metadata. Since this is being used (at least for Atlas proxy) in profile, bookmarks, owners, frequent users, this will create the user in any case before fetching the user details. 

Does that help you in any way @AustinBGibbons ?

**Comment by feng-tao** [comment]
@verdan I think we should do the same for neo4j and other proxy :) Let me take a  look at the code as well.

**Comment by verdan** [comment]
https://github.com/amundsen-io/amundsenmetadatalibrary/blob/master/metadata_service/api/user.py#L35

And the user profile part is not dependent on the proxy, so if someone has `USER_DETAIL_METHOD` configured, this will work for profile, and will create a user in metadata at least.

**Comment by feng-tao** [comment]
thanks @verdan , wasn't aware of that. Will try it out internally.

**Comment by AustinBGibbons** [comment]
Thanks for the pointer!

**Comment by AustinBGibbons** [comment]
I'm trying to add it via

```
        - name: USER_DETAIL_METHOD
          value: get_user_details
```

under `env` in `deployment-metadata.yaml`, does that seem right to you? I am not sure if my helm upgrade worked correctly

**Comment by verdan** [comment]
@AustinBGibbons do you need more help here or is it safe to close this issue?

**Comment by alldoami** [comment]
@AustinBGibbons were you able to create a `get_user_details` function that included more info about the user besides the email?

**Comment by dorianj** [comment]
Please re-open if this is still happening!
