### ISSUE TITLE
Feature Proposal - enable new line character at column level or mark down support for column level description. 

### ISSUE THREAD

**Issue by NiravLangaliya** [amundsen-io/amundsen#879]
enable new line character or markdown support at column level description. 

## Service or Ingestion ETL

frontend 
## Example Screenshots (if appropriate):
As our metadata has a short description and long description also there is other information that we want to showcase as 

**short description**: this is a short description of the column
**Long Description**: This is a long description of the column 
**Other Information**: Here is other information for the column

**Comment by feng-tao** [comment]
cc @Golodhros @allisonsuarez @ttannis 
I encounter this issue as well, do you know how to do a quick fix?

**Comment by NiravLangaliya** [comment]
Hello @feng-tao, do you think we can add this feature in near future?

**Comment by ttannis** [comment]
@feng-tao @NiravLangaliy  column descriptions should already support markdown. We use the react-markdown library so you could check their doc for how to support what you need, here's a discussion that might be relevant: https://github.com/remarkjs/react-markdown/issues/273.

Let me know if you were able to get things to work after checking how thy support new lines.

**Comment by NiravLangaliya** [comment]
I have tried to update column description by metadata api

**Comment by ttannis** [comment]
> I have tried to update column description by metadata api
> 
> using data-binary option as suggested here : https://stackoverflow.com/questions/3872427/how-to-send-line-break-with-curl
> 
> ```
> curl -X PUT "http://localhost:5002/table/dynamo%3A%2F%2Fgold.test_schema%2Ftest_table2/column/col2/description" -H "accept: application/json" -H "Content-Type: application/json" --data-binary '{
>   "description": "This is a header \n \n &nbspAnd this is a paragraph"
> }'
> ```
> 
> and also from metadata services
> ![image](https://user-images.githubusercontent.com/13895686/105304054-b2c5aa80-5be1-11eb-91a8-3aa93650ff68.png)
> 
> but it not working ,
> ![image](https://user-images.githubusercontent.com/13895686/105305000-ea345700-5be1-11eb-9b49-81022f803c4a.png)
> and at same time , it is coming correctly in neo4j description
> ![image](https://user-images.githubusercontent.com/13895686/105305570-0d5f0680-5be2-11eb-9b11-a67eecd89fce.png)
> 
> and I also tried to update it directly into Neo4j,
> 
> ```
> MERGE (d:Description {key:'dynamo://gold.test_schema/test_table2/col2/_description'})
> SET d.description = "Test from unix12 test  \n information string - nl"
> RETURN n 
> ```
> 
> but that is not working either and reflecting to Front end.
> 
> could you please share example on how to feed line breaker via CSV data source or metadata api?

@NiravLangaliya See my comment above. If your issue is that the characters are not reflecting in the UI, the place to start is checking what characters `react-markdown` library supports for new lines.

**Comment by NiravLangaliya** [comment]
@ttannis, I am trying to understand how to add new lines to support that what needs to enter or how to format the description as I want to display column description like this

**Comment by ttannis** [comment]
@NiravLangaliya column description UI should already support markdown on the frontend. If the markdown you add for new lines is not working, we use the `react-markdown` library and the suggestion was to check their doc to make sure you are entering new line syntax according to what syntax they support. 

They support GFM (github flavored markdown) and I notice that it requires the user to type `\` followed by hitting "Enter". If a user manually editing a description does that, they will get this.
![image](https://user-images.githubusercontent.com/1790900/106338161-f5bdf880-6247-11eb-8849-5de28f6fd960.png)  FYI markdown syntax is not supported in the one-line truncated version of the description, so you will see this until the column is expanded:
![image](https://user-images.githubusercontent.com/1790900/106338228-1ede8900-6248-11eb-8268-03fab0f16040.png)

**This might be the issue you're having**
I think `react-markdown` has issues displaying new line characters if the description is pre-generated and coming from another source. Here are some next steps:
1. Can you  confirm what happens if you manually update a description and type `\` then hit "Enter" to go to a new line?
2. Can you confirm what happens if you manually update a description and type `\` without hitting "Enter"?
3. Are the descriptions you are using being ingested from a backend source, but then the UI is not recognizing the new line characters?

**Comment by NiravLangaliya** [comment]
1. Can you confirm what happens if you manually update a description and type \ then hit "Enter" to go to a new line?

>   _it is giving new line as expected_

2. Can you confirm what happens if you manually update a description and type \ without hitting "Enter"?
 

> _A newline isn't coming into the description_ 

3. Are the descriptions you are using being ingested from a backend source, but then the UI is not recognizing the new line characters?

> _yes, We are trying to ingest from the backend as we have around 3000+ tables_

**Comment by ttannis** [comment]
@NiravLangaliya thanks for the update. The result here is that this not a bug with Amundsen, but rather an issue with the 3rd party library we use. Next, can you try some of the solutions mentioned in this conversation referenced in my initial comment: https://github.com/remarkjs/react-markdown/issues/273? If none of the options from that issue work, you may have to raise the issue in that repo.

**Comment by feng-tao** [comment]
I don't think this is an issue with Amundsen but more a feature request/ issue with the markdown lib we use.
