### ISSUE TITLE
User Case Implementation in Amundsen

### ISSUE THREAD

**Issue by chandaksagar** [amundsen-io/amundsen#954]
Hello Team,
We started exploring Amundsen project. 

As we try to map our use case with Amundsen, we need community help for below points 

1. We want to map our use case to Amundsen. Can we have direct call with maintainers to explain our use case and take guidance from community. It would help to understand if we can go ahead with Amundsen for implementation.
2. We wanted to check if there is a subscription based or dedicated support provided for Amundsen. If we have to implement Amundsen for our use case will there be dedicated support available (service fee based or otherwise) ?

Below is our high level similar use case we are trying to map to Amundsen.

Consider We are Financial Company 'A-FINTECH' (hypothetical) which provides financial services for Clients who want to invest money.
A-FINTECH company have multiple Agents (Employee) who can serve multiple clients at same time.

There are multiple departments in A-FINTECH company like Equity Management, Hedge Fund Management, Commission handling etc.

Every Department have multiple Agents working for it.

Single client can avail services from different departments (many to many relationship between client and Agent)

We wanted to create Client and Agent in Amundsen. Have relationship between Client and Agent defined in Amundsen.

Our basic questions for our hypothetical use case

Is it logical to put Personal profile like Client and Agent in Amundsen is correct ? If there is sample use case where it is implemented for different Personas ?
If we can can implement personal profiles, there relationship and query them in Amundsen ?

**Comment by markgrover** [comment]
Hi @chandaksagar Amundsen is a data discovery and metadata product, we do have personal profiles where additional information can be attached (see [this demo](https://www.youtube.com/watch?v=yPa1ixK1lNs&list=PL0UJdxehTNlKnGU_h7k2fzJyvAiufeh1U&index=14&t=426s).


If your use-case is simply focussed on personal profiles and has not much to do with data, then I'd suggest not using Amundsen, because it's not a good fit. The best fit for Amundsen is when you are using it for data + people together.

Feel free to re-open if I or the Amundsen community can be of any other help. Thanks for reaching out!
