### ISSUE TITLE
[bug] Watermarks for Snowflake table views not available

### ISSUE THREAD

**Issue by alldoami** [amundsen-io/amundsen#997]
## Expected Behavior
I know that Snowflake tables are not partitioned, but we would like the feature to see how old/new our data is. I'm writing a similar job to the Hive dag example to write watermarks to our tables to include the min/max date. I know it is a bit hacky as Snowflake doesn't make it easy for you to do that (takes a long time to query), so we're finding other ways to make this efficient. Along the way, I found that I'm not able to add watermarks to Snowflake table VIEWS. 

Here is what tables have (which I'm expecting in views):
![image](https://user-images.githubusercontent.com/16328889/114475374-01655e00-9bad-11eb-97b1-1d5bf16f14ea.png)

## Current Behavior
Here is what the view looks like now:
![image](https://user-images.githubusercontent.com/16328889/114475343-f01c5180-9bac-11eb-991f-7d865497ea14.png)

## Steps to Reproduce

1. Ingest any view from Snowflake.

## Your Environment

* Amunsen version used: latest
* Data warehouse stores: Snowflake
* Deployment (k8s or native): k8s

**Comment by sewardgw** [comment]
Hey @alldoami , it looks like this is working the way it is intended. Check out here, the watermarks only display for non-view tables: https://github.com/amundsen-io/amundsenfrontendlibrary/blob/df9532a89fa09f6cfe1059f4d6a300c54f277020/amundsen_application/static/js/pages/TableDetailPage/index.tsx#L426

Personally, I also think that watermarks for views makes sense and this code seems a bit too restrictive. I'd love to see this be more flexible and here are my general thoughts. Would love your input + others as well: 

Remove the validation for the is view.
```ts
  {!data.is_view && (
    <section className="metadata-section">
      <div className="section-title">
        {Constants.DATE_RANGE_TITLE}
      </div>
      <WatermarkLabel watermarks={data.watermarks} />
    </section>
...
```
to 

```ts
  {
    <section className="metadata-section">
      <div className="section-title">
        {Constants.DATE_RANGE_TITLE}
      </div>
      <WatermarkLabel watermarks={data.watermarks} />
    </section>
...
```
In turn, the watermarks should always be displayed if they exists.  In order to give users the flexibility to determine if they want to show water marks or not for views we can add a config akin to `WATER_MARK_FOR_VIEWS = True`. If users set this to False then the metadata API would return an empty list for views, even if a watermark exists.

**Comment by sewardgw** [comment]
@alldoami I believe this issue can be closed, the PR associated above makes watermarks visible for all tables and views
